from __future__ import annotations

from pathlib import Path
from typing import Optional
import datetime as dt

import pandas as pd

def write_dashboard_html(
    inst_latest: pd.DataFrame,
    pairs_latest: pd.DataFrame,
    out_dir: Path,
    as_at: Optional[dt.date] = None,
    as_of: Optional[dt.date] = None,
    release_time: Optional[str] = None,
) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    html_path = out_dir / "dashboard.html"

    def _fmt(df: pd.DataFrame) -> pd.DataFrame:
        df2 = df.copy()
        for c in df2.columns:
            if pd.api.types.is_numeric_dtype(df2[c]):
                df2[c] = df2[c].map(lambda x: "" if pd.isna(x) else f"{x:.3f}")
        return df2

    inst_tbl = _fmt(inst_latest)
    pairs_tbl = _fmt(pairs_latest)

    parts = []
    parts.append("<html><head><meta charset='utf-8'><title>COT Dashboard</title>")
    parts.append("<style>body{font-family:Arial,Helvetica,sans-serif;padding:16px;} table{border-collapse:collapse;margin:12px 0;} th,td{border:1px solid #ddd;padding:6px 8px;font-size:12px;} th{background:#f5f5f5;} h2{margin-top:24px;}</style>")
    parts.append("</head><body>")
    parts.append("<h1>COT Positioning Dashboard</h1>")
    if as_at or as_of:
        parts.append("<div>")
        if as_at:
            if release_time:
                parts.append(f"<p><strong>As at (release):</strong> {as_at.isoformat()} {release_time}</p>")
            else:
                parts.append(f"<p><strong>As at (release):</strong> {as_at.isoformat()}</p>")
        if as_of:
            parts.append(f"<p><strong>Report date (as-of):</strong> {as_of.isoformat()}</p>")
        parts.append("</div>")
    parts.append("<p>Generated by cot_bias. This is weekly, lagged positioning (bias filter, not a trigger).</p>")
    parts.append("<h2>Instruments (latest)</h2>")
    parts.append(inst_tbl.to_html(index=False, escape=True))
    parts.append("<h2>FX Pairs (derived)</h2>")
    parts.append(pairs_tbl.to_html(index=False, escape=True))
    parts.append("</body></html>")

    html_path.write_text("\n".join(parts), encoding="utf-8")
    return html_path
